#!/usr/bin/env python3
"""Generate per-table GCP startup scripts for every host.

The shared header lives in gcp_common_startup.sh (this directory).
Each host provides gcp_*_startup.tail.sh fragments with its specific commands.
Run from any directory:

    python src/metadata_tools/hosts/generate_startup_scripts.py
"""
from pathlib import Path

_HOSTS_DIR = Path(__file__).parent
_DIVIDER = '#' * 89


def _build(common: str, tail_name: str, tail: str) -> str:
    return (
        '#!/bin/bash\n'
        '# Generated by generate_startup_scripts.py — edit gcp_common_startup.sh\n'
        f'# or {tail_name} instead of modifying this file directly.\n'
        '\n'
        + _DIVIDER + '\n'
        + common.rstrip('\n') + '\n'
        + _DIVIDER + '\n'
        '\n'
        + tail
    )


def main() -> None:
    common = (_HOSTS_DIR / 'gcp_common_startup.sh').read_text()
    host_dirs = sorted(p for p in _HOSTS_DIR.iterdir() if p.is_dir() and not p.name.startswith('_'))
    for host_dir in host_dirs:
        for tail_file in sorted(host_dir.glob('gcp_*_startup.tail.sh')):
            out_name = tail_file.name.replace('.tail.sh', '.sh')
            content = _build(common, tail_file.name, tail_file.read_text())
            out = host_dir / out_name
            out.write_text(content)
            print(f'Generated {host_dir.name}/{out.name}')


if __name__ == '__main__':
    main()
