provider: gcp
gcp:
  job_id:                   metadata_geometry-job
  project_id:               rms-metadata
  startup_script_file:      gcp_geometry_startup.sh
  service_account:          rms-metadata-tools@rms-metadata.iam.gserviceaccount.com
  max_runtime:              10000
  region:                   us-central1
  max-instances:            10
#  max-cpu:                  8
#  min-memory-per-cpu:       4  # GB
#  max-total-price-per-hour: 2.00  # USD/hour
#  instance-types:           "n2-"
