provider: gcp
gcp:
  job_id:                   metadata-cumulative-job
  project_id:               rms-metadata
  service_account:          rms-metadata-tools-154@rms-metadata.iam.gserviceaccount.com
  region:                   us-central1
  zone:                     us-central1-a

  instance_types:           ["^n2-.*", "^n3-.*", "^n4-.*"]
  boot_disk_types:          pd-balanced
  max_instances:            2
  cpus_per_task:            1
  min_memory_per_task:      8

  max_runtime:              10000
  max_cpu:                  4


  startup_script_file:      gcp_cumulative_startup.sh


