"""Column computation catalog for ring geometry tables.

This module names every ring geometry column this package knows how to compute
and says how: the backplane key describing ring-plane and ansa geometry, the
bodies that mask it, and the unit conversion applied to the result.

Whether a column is actually produced -- and in what order, with what width,
null value, and valid range -- is decided by the host's label template, not
here. An entry no template names is simply unused. See
:mod:`metadata_tools.columns.catalog`.
"""
import metadata_tools.defs as defs
import metadata_tools.util as util
from metadata_tools.columns.catalog import ColumnSpec, minmax, pair, single

planet_ring = defs.BODYX + ":RING"
planet_ansa = defs.BODYX + ":ANSA"

RING_CATALOG: tuple[ColumnSpec, ...] = (
    minmax('RING_RADIUS', ('ring_radius', planet_ring),
           ('PM', 'P', '')),
    pair('FINEST_RING_INTERCEPT_RESOLUTION', 'COARSEST_RING_INTERCEPT_RESOLUTION',
         ('resolution', planet_ring, 'v'),
         ('PM', 'P', '')),
    pair('FINEST_RADIAL_RESOLUTION', 'COARSEST_RADIAL_RESOLUTION',
         ('ring_radial_resolution', planet_ring),
         ('PM', 'P', '')),
    pair('FINEST_LONGITUDINAL_RESOLUTION', 'COARSEST_LONGITUDINAL_RESOLUTION',
         ('ring_angular_resolution', planet_ring),
         ('PM', 'P', '')),
    pair('FINEST_LONGITUDINAL_RESOLUTION_KM', 'COARSEST_LONGITUDINAL_RESOLUTION_KM',
         ('ring_angular_resolution', planet_ring, 'km'),
         ('PM', 'P', ''), alt='km'),
    minmax('RING_DISTANCE', ('distance', planet_ring),
           ('PM', 'P', '')),
    minmax('RING_LONGITUDE', ('ring_longitude', planet_ring, 'aries'),
           ('PM', 'P', '')),
    minmax('RING_LONGITUDE_WRT_NODE', ('ring_longitude', planet_ring, 'node'),
           ('PM', 'P', '')),
    minmax('SOLAR_HOUR_ANGLE', ('ring_longitude', planet_ring, 'sha'),
           ('PM', '', '')),
    minmax('RING_LONGITUDE_WRT_OBSERVER', ('ring_longitude', planet_ring, 'obs'),
           ('PM', 'P', ''), alt='-180'),
    minmax('RING_AZIMUTH', ('ring_azimuth', planet_ring, 'obs'),
           ('PM', 'P', '')),
    minmax('RING_PHASE_ANGLE', ('phase_angle', planet_ring),
           ('PM', 'P', '')),
    minmax('RING_INCIDENCE_ANGLE', ('ring_incidence_angle', planet_ring),
           ('PM', 'P', '')),
    minmax('NORTH_BASED_INCIDENCE_ANGLE', ('ring_incidence_angle', planet_ring, 'prograde'),
           ('PM', 'P', '')),
    minmax('RING_EMISSION_ANGLE', ('ring_emission_angle', planet_ring),
           ('PM', 'P', '')),
    minmax('NORTH_BASED_EMISSION_ANGLE', ('ring_emission_angle', planet_ring, 'prograde'),
           ('PM', 'P', '')),
    minmax('SOLAR_RING_ELEVATION', ('ring_elevation', planet_ring, 'sun'),
           ('PM', 'P', '')),
    minmax('OBSERVER_RING_ELEVATION', ('ring_elevation', planet_ring, 'obs'),
           ('PM', 'P', '')),
    minmax('RING_INTERCEPT_TIME', ('event_time', planet_ring),
           ('PM', 'P', '')),
    minmax('EDGE_ON_RING_RADIUS', ('ansa_radius', planet_ansa),
           ('PM', 'P', '')),
    minmax('EDGE_ON_RING_ALTITUDE', ('ansa_altitude', planet_ansa),
           ('PM', 'P', '')),
    pair('FINEST_EDGE_ON_RADIAL_RESOLUTION', 'COARSEST_EDGE_ON_RADIAL_RESOLUTION',
         ('ansa_radial_resolution', planet_ansa),
         ('PM', 'P', '')),
    minmax('EDGE_ON_INTERCEPT_DISTANCE', ('distance', planet_ansa),
           ('PM', 'P', '')),
    minmax('EDGE_ON_RING_LONGITUDE', ('ansa_longitude', planet_ansa, 'aries'),
           ('PM', 'P', '')),
    minmax('EDGE_ON_RING_LONGITUDE_WRT_NODE', ('ansa_longitude', planet_ansa, 'node'),
           ('PM', 'P', '')),
    minmax('EDGE_ON_SOLAR_HOUR_ANGLE', ('ansa_longitude', planet_ansa, 'sha'),
           ('PM', 'P', '')),
    minmax('RING_CENTER_DISTANCE', ('center_distance', planet_ring, 'obs'),
           ('', '', '')),
    minmax('SUB_SOLAR_RING_LONGITUDE', ('ring_sub_solar_longitude', planet_ring, 'aries'),
           ('', '', '')),
    minmax('SUB_SOLAR_RING_LONGITUDE_WRT_NODE', ('ring_sub_solar_longitude', planet_ring, 'node'),
           ('', '', '')),
    minmax('SUB_OBSERVER_RING_LONGITUDE', ('ring_sub_observer_longitude', planet_ring, 'aries'),
           ('', '', '')),
    minmax('SUB_OBSERVER_RING_LONGITUDE_WRT_NODE',
           ('ring_sub_observer_longitude', planet_ring, 'node'),
           ('', '', '')),
    minmax('RING_CENTER_PHASE_ANGLE', ('center_phase_angle', planet_ring),
           ('', '', '')),
    minmax('RING_CENTER_INCIDENCE_ANGLE', ('ring_center_incidence_angle', planet_ring),
           ('', '', '')),
    minmax('NORTH_BASED_CENTER_INCIDENCE_ANGLE',
           ('ring_center_incidence_angle', planet_ring, 'prograde'),
           ('', '', '')),
    minmax('RING_CENTER_EMISSION_ANGLE', ('ring_center_emission_angle', planet_ring),
           ('', '', '')),
    minmax('NORTH_BASED_CENTER_EMISSION_ANGLE',
           ('ring_center_emission_angle', planet_ring, 'prograde'),
           ('', '', '')),
    minmax('SOLAR_RING_CENTER_OPENING_ANGLE', ('sub_solar_latitude', planet_ring),
           ('', '', '')),
    minmax('OBSERVER_RING_CENTER_OPENING_ANGLE', ('sub_observer_latitude', planet_ring),
           ('', '', '')),
    single('RING_DIAMETER_IN_PIXELS',
           ('body_diameter_in_pixels', planet_ring,
            util.replacement_fn('defs.RING_SYSTEM_RADII', defs.BODYX)),
           ('', '', '')),
    single('RING_POLE_CLOCK_ANGLE', ('pole_clock_angle', defs.BODYX),
           ('', '', '')),
    single('RING_POLE_POSITION_ANGLE', ('pole_position_angle', defs.BODYX),
           ('', '', '')),
    single('RING_CENTER_X_COORDINATE', ('center_coordinate', defs.BODYX, 'u'),
           ('', '', '')),
    single('RING_CENTER_Y_COORDINATE', ('center_coordinate', defs.BODYX, 'v'),
           ('', '', '')),
)
"""Every ring column this package can compute, keyed by template NAME."""
