#!/bin/bash
# Generated by generate_startup_scripts.py — edit gcp_common_startup.sh
# or gcp_index_startup.tail.sh instead of modifying this file directly.

#########################################################################################
# Mount OOPS-Resources
export INSTANCE_NAME=$(curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/name)
gcloud compute instances attach-disk $INSTANCE_NAME --disk=standard-oops-resources-central1-a-1 --zone=us-central1-a --device-name=nav-resources --mode ro

sudo mkdir -p /mnt/nav-resources
sudo mount -o ro /dev/disk/by-id/google-nav-resources-part1 /mnt/nav-resources
export OOPS_RESOURCES=/mnt/nav-resources/OOPS-Resources/

# sudo needed for manual paste into instance terminal.
sudo apt-get update -y
sudo apt-get install -y python3 python3-pip python3-venv git
cd

#git clone https://github.com/SETI/rms-metadata-tools.git
git clone -b jns-updates-claude --single-branch https://github.com/SETI/rms-metadata-tools.git
cd rms-metadata-tools
python3 -m venv venv
source venv/bin/activate
pip install ".[cloud]"
#########################################################################################

# Run the index code
metadata-index-cloud GO_0xxx \
                gs://rms-node-holdings/pds3-holdings/volumes/GO_0xxx/ \
                gs://rms-node-holdings/pds3-holdings/metadata/GO_0xxx/ \
                gs://rms-metadata-jspitale/metadata_test/GO_0xxx/

##  Manual paste into instance..
: <<'COMMENT_BLOCK'
gcloud auth application-default login
metadata-index GO_0xxx \
                gs://rms-node-holdings/pds3-holdings/volumes/GO_0xxx/ \
                gs://rms-node-holdings/pds3-holdings/metadata/GO_0xxx/ \
                gs://rms-metadata-jspitale/metadata_test/GO_0xxx/ -vv GO_0022
COMMENT_BLOCK
